services:
    php:
        build:
            args:
                user: anderson
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: escuteiros
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

        networks:
            - escuteiros

    redis:
        image: redis:alpine
        networks:
            - escuteiros


    nginx:
        image: nginx:stable-alpine
        ports:
            - "8081:80"
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/

        networks:
            - escuteiros


    mysql:
        image: mysql:latest
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - escuteiros


    phpMyAdmin:
        image: phpmyadmin:fpm-alpine

        depends_on:
            - "mysql"

        ports: "8082:80"

        environment:
            - PMA_ARBITRARY=1

        networks:
            - escuteiros


networks:
    escuteiros:
        driver: bridge
